// vuejs/ssr/nuxt.js/pages/index.vue
<template>
  <section>
    <h1>Batman TV Shows</h1>
    <ul>
      <li v-for="item in items" :key="item.show.id">
        <nuxt-link :to="'/post/' + item.show.id"> {{ item.show.name }} </nuxt-link>
      </li>
    </ul>
  </section>
</template>

<script>
import fetch from 'isomorphic-unfetch'

export default {
  async asyncData ({store, isServer}) {
    const res = await fetch('https://api.tvmaze.com/search/shows?q=batman')
    const data = await res.json()

    console.log(`Show data fetched. Count: ${data.length}`)

    // Save isServer for demo purposes
    store.commit('rendered', isServer)

    return {
      items: data,
      isServer
    }
  }
}
</script>

// react/ssr/next.js/pages/index.js
import Layout from '../components/MyLayout.js'
import Link from 'next/link'
import fetch from 'isomorphic-unfetch'

const Index = (props) => (
  <Layout isServer={props.isServer}>
    <h1>Batman TV Shows</h1>
    <ul>
      {props.shows.map(({show}) => (
        <li key={show.id}>
          <Link as={`/p/${show.id}`} href={`/post?id=${show.id}`}>
            <a>{show.name}</a>
          </Link>
        </li>
      ))}
    </ul>
    <style jsx>{`
        h1, a {
        font-family: "Arial";
        }

        ul {
        padding: 0;
        }

        li {
        list-style: none;
        margin: 5px 0;
        }

        a {
        text-decoration: none;
        color: blue;
        }

        a:hover {
        opacity: 0.6;
        }
    `}</style>
  </Layout>
)

Index.getInitialProps = async ({req}) => {
  const res = await fetch('https://api.tvmaze.com/search/shows?q=batman')
  const data = await res.json()

  console.log(`Show data fetched. Count: ${data.length}`)

  return {
    shows: data,
    isServer: !!req
  }
}

export default Index
